"""EDA の図と数表を reports/ に書き出す。

出力:
  reports/figures/eda_*.png
  reports/eda_summary.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from ett_poc.data import LOAD_COLS, STEPS_PER_HOUR, TARGET, Split, load  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "reports" / "figures"
FIG.mkdir(parents=True, exist_ok=True)
plt.rcParams.update({"font.family": "Arial", "figure.dpi": 130, "axes.grid": True, "grid.alpha": 0.3})

lines: list[str] = ["# EDA summary (auto-generated by scripts/run_eda.py)", ""]


def out(s: str = "") -> None:
    lines.append(s)


for name in ["ETTh1", "ETTh2"]:
    df = load(name)
    sph = STEPS_PER_HOUR[name]
    split = Split.default(df.index)
    tr, va, te = split.masks(df.index)
    out(f"## {name}")
    out(f"- rows={len(df)}, period={df.index[0]:%Y-%m-%d}..{df.index[-1]:%Y-%m-%d}")
    out(f"- split: train<{split.train_end:%Y-%m-%d} ({tr.sum()}), valid<{split.valid_end:%Y-%m-%d} ({va.sum()}), test ({te.sum()})")
    d = df[TARGET].describe()
    out(f"- OT mean={d['mean']:.2f} std={d['std']:.2f} min={d['min']:.2f} max={d['max']:.2f}; "
        f"quantiles 90/95/99% = {df[TARGET].quantile(.9):.1f}/{df[TARGET].quantile(.95):.1f}/{df[TARGET].quantile(.99):.1f}")
    corr = df.corr()[TARGET].drop(TARGET).round(3).to_dict()
    out(f"- corr(load, OT) at same time: {corr}")
    ac = {f"{h}h": round(df[TARGET].autocorr(h * sph), 3) for h in (1, 6, 24, 168)}
    out(f"- OT autocorrelation: {ac}")

    # 1) 全期間の OT と月平均
    fig, ax = plt.subplots(figsize=(11, 3.2))
    ax.plot(df.index, df[TARGET], lw=0.4, color="#3f55a8", label="OT (hourly)")
    ax.plot(df[TARGET].resample("ME").mean().index, df[TARGET].resample("ME").mean(), lw=2, color="#b9642a", label="monthly mean")
    ax.axvline(split.train_end, color="k", ls="--", lw=0.8)
    ax.axvline(split.valid_end, color="k", ls="--", lw=0.8)
    ax.set_title(f"{name}: oil temperature over the full period (dashed = train/valid/test split)")
    ax.set_ylabel("OT [°C]")
    ax.legend(loc="upper right")
    fig.tight_layout()
    fig.savefig(FIG / f"eda_{name}_ot_timeline.png")
    plt.close(fig)

    # 2) 日内周期（時刻別の平均、季節ごと）
    hourly = df.copy()
    hourly["hour"] = hourly.index.hour
    hourly["season"] = pd.cut(hourly.index.month, [0, 2, 5, 8, 11, 12], labels=["DJF", "MAM", "JJA", "SON", "DJF2"], right=True)
    hourly["season"] = hourly["season"].replace({"DJF2": "DJF"})
    prof = hourly.groupby(["season", "hour"], observed=True)[TARGET].mean().unstack(0)
    fig, ax = plt.subplots(figsize=(6.5, 3.4))
    prof.plot(ax=ax)
    ax.set_title(f"{name}: mean OT by hour of day, per season")
    ax.set_xlabel("hour of day")
    ax.set_ylabel("OT [°C]")
    fig.tight_layout()
    fig.savefig(FIG / f"eda_{name}_diurnal.png")
    plt.close(fig)
    amp = (prof.max() - prof.min()).round(2).to_dict()
    out(f"- diurnal amplitude (max-min of hourly mean) by season: {amp}")

    # 3) 負荷と OT の散布（同時刻）と、ラグ付き相互相関
    fig, axes = plt.subplots(1, 3, figsize=(11, 3.3))
    for ax, c in zip(axes, ["HUFL", "MUFL", "LUFL"]):
        ax.scatter(df[c], df[TARGET], s=2, alpha=0.15, color="#3f55a8")
        ax.set_xlabel(c)
        ax.set_ylabel("OT")
        ax.set_title(f"corr={df[c].corr(df[TARGET]):.2f}")
    fig.suptitle(f"{name}: same-time load vs OT")
    fig.tight_layout()
    fig.savefig(FIG / f"eda_{name}_load_scatter.png")
    plt.close(fig)

    lags = list(range(0, 49, 1))
    fig, ax = plt.subplots(figsize=(7, 3.2))
    xcorr = {}
    for c in ["HUFL", "MUFL", "LUFL"]:
        vals = [df[TARGET].corr(df[c].shift(l * sph)) for l in lags]
        xcorr[c] = vals
        ax.plot(lags, vals, label=c)
    ax.axhline(0, color="k", lw=0.6)
    ax.set_xlabel("lag of load [h] (load leads OT)")
    ax.set_ylabel("corr(OT[t], load[t-lag])")
    ax.set_title(f"{name}: cross-correlation of loads leading OT")
    ax.legend()
    fig.tight_layout()
    fig.savefig(FIG / f"eda_{name}_xcorr.png")
    plt.close(fig)
    best = {c: (int(np.nanargmax(np.abs(v))), round(float(v[int(np.nanargmax(np.abs(v)))]), 3)) for c, v in xcorr.items()}
    out(f"- strongest lead-lag corr (lag h, corr): {best}")

    # 4) 変化率の分布（急変がどれだけあるか）
    dOT = df[TARGET].diff(sph)
    out(f"- 1h change of OT: std={dOT.std():.2f}, |dOT|>2°C share={(dOT.abs() > 2).mean():.3%}, |dOT|>5°C share={(dOT.abs() > 5).mean():.4%}")

    # 5) 持続予測 MAE（ホライズン別）と季節ナイーブ
    row = []
    for h in (1, 6, 24):
        persist = (df[TARGET].shift(h * sph) - df[TARGET]).abs()
        seasonal = (df[TARGET].shift(24 * sph) - df[TARGET]).abs() if h <= 24 else None
        row.append(f"h={h}h persist MAE test={persist[te].mean():.3f}")
    out("- naive baselines on test: " + "; ".join(row) + f"; seasonal-naive(24h) MAE test={(df[TARGET].shift(24*sph)-df[TARGET]).abs()[te].mean():.3f}")
    out()

# 6) 2 台の比較（同一期間の OT 分布）
h1, h2 = load("ETTh1"), load("ETTh2")
fig, ax = plt.subplots(figsize=(6.5, 3.2))
ax.hist(h1[TARGET], bins=60, alpha=0.6, label="ETTh1", color="#3f55a8")
ax.hist(h2[TARGET], bins=60, alpha=0.6, label="ETTh2", color="#b9642a")
ax.set_xlabel("OT [°C]")
ax.set_ylabel("count")
ax.set_title("OT distribution: transformer 1 vs 2")
ax.legend()
fig.tight_layout()
fig.savefig(FIG / "eda_ot_hist_h1_h2.png")
plt.close(fig)

(ROOT / "reports" / "eda_summary.md").write_text("\n".join(lines), encoding="utf-8")
print("\n".join(lines))
