"""ベースライン（B0 持続・B1 季節ナイーブ・B2 リッジ）を検証・テストで評価する。

出力: reports/results_baselines.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from ett_poc.data import STEPS_PER_HOUR, TARGET, Split, load  # noqa: E402
from ett_poc.evaluate import onset_metrics, regression_metrics, state_metrics  # noqa: E402
from ett_poc.features import CONDITION_B, check_no_leakage, columns_for, make_features, make_target  # noqa: E402
from ett_poc.models import fit_ridge  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
HORIZONS = [1, 6, 24]


def evaluate_all(name, h, sph, split, Xa, ya, preds, thresholds, rows):
    tr, va, te = split.masks_by_target(Xa.index, pd.Timedelta(hours=h))
    for label, p in preds.items():
        for part, mask in [("valid", va), ("test", te)]:
            m = regression_metrics(ya[mask], p[mask])
            row = {"dataset": name, "horizon_h": h, "model": label, "split": part,
                   "MAE": round(m["MAE"], 3), "RMSE": round(m["RMSE"], 3), "n": m["n"]}
            for q, thr in thresholds.items():
                st = state_metrics(ya[mask], p[mask], thr, 24 * sph)
                on = onset_metrics(Xa.loc[mask, "ot_now"], ya[mask], p[mask], thr, 24 * sph, pd.Timedelta(hours=h))
                row.update({
                    f"q{q}_events": st["events"], f"q{q}_recall": round(st["recall"], 3),
                    f"q{q}_onset_events": on["events_with_onset"], f"q{q}_onset_recall": round(on["event_recall"], 3),
                    f"q{q}_notices/day": round(on["notices_per_day"], 2), f"q{q}_false_notices/day": round(on["false_notices_per_day"], 2),
                })
            rows.append(row)


def main() -> None:
    rows = []
    for name in ["ETTh1", "ETTh2"]:
        df = load(name)
        sph = STEPS_PER_HOUR[name]
        split = Split.default(df.index)
        tr_time, _, _ = split.masks(df.index)
        thresholds = {95: float(df.loc[tr_time, TARGET].quantile(0.95)), 90: float(df.loc[tr_time, TARGET].quantile(0.90))}
        for h in HORIZONS:
            check_no_leakage(df, sph, h)
            X, groups = make_features(df, sph, h)
            y = make_target(df, h, sph)
            cols_b = columns_for(groups, CONDITION_B)
            m = X[cols_b].notna().all(axis=1) & y.notna()
            Xa, ya = X[m], y[m]
            tr, va, te = split.masks_by_target(Xa.index, pd.Timedelta(hours=h))

            preds = {
                "B0_persistence": Xa["ot_now"],
                "B1_seasonal24h": df[TARGET].shift((24 - h) * sph).reindex(Xa.index),
            }
            ridge = fit_ridge(Xa.loc[tr, cols_b], ya[tr])
            preds["B2_ridge(B)"] = pd.Series(ridge.predict(Xa[cols_b]), index=Xa.index)
            evaluate_all(name, h, sph, split, Xa, ya, preds, thresholds, rows)
        print(name, "thresholds", {k: round(v, 1) for k, v in thresholds.items()})

    res = pd.DataFrame(rows)
    out = ["# Baselines (auto-generated by scripts/run_baselines.py)", "",
           "閾値 q95/q90 = 学習期間の OT 上位 5%/10% 点（設備ごとに固定）。",
           "`events` = 対象時刻に閾値を超える連続区間の数、`recall` = 時点単位の高温状態の再現率、",
           "`onset_events` = 起点では閾値以下で対象時刻に超えるイベント数、`onset_recall` = そのイベントを事前に警報できた割合、",
           "`notices/day` = 起点が閾値以下のときの警報を連続で 1 通にまとめた通知数/日。", ""]
    for part in ["valid", "test"]:
        out.append(f"## {part}")
        out.append(res[res.split == part].drop(columns=["split"]).to_markdown(index=False))
        out.append("")
    (ROOT / "reports" / "results_baselines.md").write_text("\n".join(out), encoding="utf-8")
    res.to_csv(ROOT / "reports" / "results_baselines.csv", index=False)
    print("\n".join(out))


if __name__ == "__main__":
    main()
