"""6h 先の改善が期間によって安定しているかを、対象月・対象週ごとの MAE で確認する。
持続予測・リッジ・LightGBM（条件 B）を同じ行で比較する。

出力: reports/results_stability.md, reports/results_stability.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from ett_poc.data import STEPS_PER_HOUR, Split, load  # noqa: E402
from ett_poc.features import CONDITION_B, columns_for, make_features, make_target  # noqa: E402
from ett_poc.models import fit_ridge  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
REP = ROOT / "reports"
H = 6
rows, wrows = [], []
for name in ["ETTh1", "ETTh2"]:
    df = load(name)
    sph = STEPS_PER_HOUR[name]
    split = Split.default(df.index)
    X, groups = make_features(df, sph, H)
    y = make_target(df, H, sph)
    cols = columns_for(groups, CONDITION_B)
    m = X[cols].notna().all(axis=1) & y.notna()
    Xa, ya = X[m], y[m]
    tr, va, te = split.masks_by_target(Xa.index, pd.Timedelta(hours=H))
    ridge = fit_ridge(Xa.loc[tr, cols], ya[tr])
    lgb = pd.read_csv(REP / "predictions" / f"{name}_h{H}_B.csv", index_col=0, parse_dates=True)["pred"]
    preds = {
        "B0_persistence": Xa["ot_now"],
        "B2_ridge(B)": pd.Series(ridge.predict(Xa[cols]), index=Xa.index),
        "M1_lgbm(B)": lgb.reindex(Xa.index),
    }
    tidx = Xa.index[te] + pd.Timedelta(hours=H)
    for label, p in preds.items():
        err = (p[te] - ya[te]).abs()
        by_m = err.groupby(tidx.to_period("M")).mean()
        for per, v in by_m.items():
            rows.append({"dataset": name, "horizon_h": H, "model": label, "target_month": str(per), "MAE": round(float(v), 3)})
        by_w = err.groupby(tidx.to_period("W")).mean()
        for per, v in by_w.items():
            wrows.append({"dataset": name, "model": label, "target_week": str(per), "MAE": float(v)})

res = pd.DataFrame(rows)
wk = pd.DataFrame(wrows)
out = ["# Stability of the 6h improvement (auto-generated by scripts/run_stability.py)", "",
       "テスト期間を対象時刻の月で切った MAE。週単位は「LightGBM が持続／リッジより良かった週の割合」。", ""]
for name in ["ETTh1", "ETTh2"]:
    piv = res[res.dataset == name].pivot(index="target_month", columns="model", values="MAE")
    piv["impr_vs_persistence"] = (1 - piv["M1_lgbm(B)"] / piv["B0_persistence"]).round(3)
    piv["impr_vs_ridge"] = (1 - piv["M1_lgbm(B)"] / piv["B2_ridge(B)"]).round(3)
    out.append(f"## {name} (h={H}h, condition B)")
    out.append(piv.to_markdown())
    w = wk[wk.dataset == name].pivot(index="target_week", columns="model", values="MAE")
    out.append("")
    out.append(f"- weeks: {len(w)}; LightGBM better than persistence in {(w['M1_lgbm(B)'] < w['B0_persistence']).mean():.0%} of weeks, "
               f"better than ridge in {(w['M1_lgbm(B)'] < w['B2_ridge(B)']).mean():.0%} of weeks")
    out.append("")
(REP / "results_stability.md").write_text("\n".join(out), encoding="utf-8")
res.to_csv(REP / "results_stability.csv", index=False)
print("\n".join(out))
